---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kbtech.org # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: kbtech-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.kbtech.org" # change to your domain
  dnsNames:
  - "*.kbtech.org" # change to your domain
  - kbtech.org # change to your domain
